services:
  - name: app
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env:
      - key: PORT
        value: 5000
      - key: RENDER
        value: true
    ports:
      - 5000
``
